### ISSUE TITLE
Oh no!

### ISSUE THREAD

**Issue by jonas-schievink** [conradkleinespel/rustastic-password#11]
When aborting password entry with Ctrl+D (on Linux, but I'd imagine it's the same on OS X), `read_password` returns an error that reads "oh no!". It should probably return a more descriptive error.

**Comment by conradkleinespel** [comment]
@jonas-schievink Hello ! Thanks for the suggestion. You are 100% right. What would be a good, descriptive, error message for Ctrl+D ? This basically happens anytime there is not enough input, so maybe [UnexpectedEof](https://doc.rust-lang.org/std/io/enum.ErrorKind.html#variant.UnexpectedEof) would be OK ?

**Comment by jonas-schievink** [comment]
Yes, that sounds good!

**Comment by conradkleinespel** [comment]
@jonas-schievink Awesome ! Just pushed a [commit](https://github.com/conradkleinespel/rustastic-password/commit/d2b971086cfe014676e9f0ffffa78747131219c2) that fixes that. I've bumped the minor version number as this is a breaking change.
