### ISSUE TITLE
could not parse input as TOML

### ISSUE THREAD

**Issue by MeanderingCode** [conradkleinespel/rustastic-password#14]
Cargo 0.8.0 is failing to build rpassword as a dependency.

```
 Downloading rpassword v0.2.2
unable to get packages from source

Caused by:
  failed to parse manifest at `/home/meanderingcode/.cargo/registry/src/github.com-48ad6e4054423464/rpassword-0.2.2/Cargo.toml`

Caused by:
  could not parse input as TOML
/home/meanderingcode/.cargo/registry/src/github.com-48ad6e4054423464/rpassword-0.2.2/Cargo.toml:13:9 expected a key but found an empty string
/home/meanderingcode/.cargo/registry/src/github.com-48ad6e4054423464/rpassword-0.2.2/Cargo.toml:13:9-13:10 expected `.`, but found `'`
```

**Comment by MeanderingCode** [comment]
https://github.com/conradkleinespel/rustastic-password/blob/master/Cargo.toml#L13
`[target.'cfg(not(windows))'.dependencies`

I could not find another Cargo.toml in the dependencies of the project that has such a line, beggining with `[target`.

**Comment by MeanderingCode** [comment]
This is due to using Cargo 0.8.0, which does not support the particular `[target.'` syntax.

Works in Cargo 0.9.0.  Closing.

**Comment by conradkleinespel** [comment]
@MeanderingCode Yes, exactly, this is meant to work with Cargo 0.9. Sorry for any confusion.
