### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jethrogb** [conradkleinespel/rustastic-password#15]
Which license is this crate? [Cargo.toml says Apache](https://github.com/conradkleinespel/rustastic-password/blob/master/Cargo.toml#L7) but [README.md says MIT](https://github.com/conradkleinespel/rustastic-password/blame/master/README.md#L11). Or is it both such as most Cargo crates?

**Comment by conradkleinespel** [comment]
@jethrogb You bring up a good point. I don't think I am allowed to re-license code without contributors' agreement so I will ask every contributor here.

To the following people, do you agree to license your contributions under the terms of the [Apache 2.0 license](http://www.apache.org/licenses/LICENSE-2.0) ?

@dcuddeback
@equalsraf
@petevine
@psych0d0g
@retep998

**Comment by petevine** [comment]
No objection here.

**Comment by retep998** [comment]
Either or both license is fine by me.

**Comment by equalsraf** [comment]
Either case is fine by me

**Comment by dcuddeback** [comment]
Either is okay with me.

**Comment by conradkleinespel** [comment]
Thanks a lot for your quick replies @petevine @retep998 @equalsraf and @dcuddeback ! @psych0d0g, what do you think ?

**Comment by conradkleinespel** [comment]
Terribly sorry to bother you with this @psych0d0g but I think I'm legally required to ask for your consent here. Would you be OK with relicensing your contribution as Apache 2.0 ?

**Comment by retep998** [comment]
@conradkleinespel Try emailing @psych0d0g with the email address attached to one of their commits.

**Comment by jethrogb** [comment]
His commits are merely [some changes to Cargo.toml](https://github.com/conradkleinespel/rustastic-password/commits/master?author=psych0d0g) that from the looks of it might not be copyrightable.

**Comment by retep998** [comment]
Especially since all of those lines have since been rewritten anyway, so even if it was copyrightable it no longer applies to the current version.

**Comment by conradkleinespel** [comment]
Sorry for taking so long. @jethrogb and @retep998, you are 100% right. I've clarified licensing so it now clearly says Apache 2.0 everywhere. Thanks all !
