### ISSUE TITLE
Re-add windows support

### ISSUE THREAD

**Issue by retep998** [conradkleinespel/rustastic-password#5]
Reminder to myself to do this.

**Comment by conradkleinespel** [comment]
Hi @retep998,

Awesome to see you're still interested in this ! :+1: 

I don't use Windows and have no Windows license so it's hard for me to support this platform. And I kinda had to drop Windows support since it was broken with `rustc` updates in the last few weeks. However, I will gladly merge a patch if you have and take the time to create it.

Take care,
Conrad

**Comment by equalsraf** [comment]
Cheers, is anyone looking into this? I have a quick fix using the original source from #2, in [here](https://github.com/equalsraf/rustastic-password/tree/tb-windows). Seems to work ok with Rust 1.0 here.

**Comment by conradkleinespel** [comment]
Hi @equalsraf,

Thanks a lot for your work ! :+1: 

If you have a patch and make a working pull request, I'm glad to merge.

On that note, I'm a Mac/Linux user and don't have Windows. Would you be interested in getting commit access to maintain the Windows version ? Same question to you, @retep998, in case you're interested :-)

Cheers,
Conrad

**Comment by equalsraf** [comment]
Honestly this is my first bit of public rust ever :grinning: and I don't spend that long in front of Windows, but I can give it a shot.

**Comment by equalsraf** [comment]
Incidentally if you want, it seems easy enough to enable [CI builds](https://ci.appveyor.com/project/equalsraf/rustastic-password/build/1.0.6) for windows (well there are no tests for windows yet, but at least it builds the example).

**Comment by conradkleinespel** [comment]
Thanks a lot for your contribution @equalsraf !

This issue is resolved per: https://github.com/conradkleinespel/rustastic-password/commit/1b77c90aff38837b6e9b1b8b41e066cb2c6e5a81

**Comment by conradkleinespel** [comment]
I've updated the version and pushed it to crates.io.
