### ISSUE TITLE
The example in README does not work

### ISSUE THREAD

**Issue by JanLikar** [conradkleinespel/rustastic-password#7]
On my computer (Latest Ubuntu) "Type a password: " gets printed into the terminal only after entering the password. This happens because print! macro doesn't flush output buffers. There are two solutions: example could be fixed to manually flush the buffer or read_password() could be modified to implicitly flush it.

I am willing to create a pull request, if you want me to.

**Comment by conradkleinespel** [comment]
Hi @JanLikar,

Thanks a lot for bringing this up ! :+1: 

I will correct the example. Are you OK with me adding you as a contributor ?

Best regards,
Conrad

**Comment by JanLikar** [comment]
You're welcome. And yes, you can add me.

**Comment by conradkleinespel** [comment]
Awesome, thanks !
